version: 0.2
phases:
  pre_build:
    - echo "Pre build phase - fazer algumas badaroscas"
  build:
    commands:
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Post Building"
      - mv target/*.war ./ROOT/war
artifacts:
  files:
    - ROOT.war